name: Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Newline
        run: |
          NEWLINE=$(cat << EOF
          EOF)
          NEWLINE="${NEWLINE//'%'/'%25'}"
          NEWLINE="${NEWLINE//$'\n'/'%0A'}"
          NEWLINE="${NEWLINE//$'\r'/'%0D'}"
          echo "::set-output name=content::$NEWLINE"
        id: newline
        
      - name: Current Date
        run: echo "::set-output name=content::$(date +'%Y-%m-%d %H:%M:%S')"
        id: now-name

      - name: Current Date
        run: echo "::set-output name=content::$(date +'%Y-%m-%d-%H-%M-%S')"
        id: now-tag
        
      - uses: actions/checkout@v2
        with:
          path: electron
          
      - uses: actions/checkout@v2
        with:
          repository: kernel-mod/browser
          path: browser
          
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - uses: pnpm/action-setup@v2.0.1   
        with:  
          version: 6.20.1
          
      - name: Build ASAR
        run: |
          cd browser
          pnpm i
          cd ../electron
          pnpm i
          pnpm run build

      - name: Download Latest Release
        # You may pin to the exact commit or the version.
        # uses: robinraju/release-downloader@95181030e3b4d574d027e8f4bb7d97fc62331c35
        uses: robinraju/release-downloader@v1.2
        with:
          # A flag to choose between latest release and remaining releases
          latest: true
          # Name of the file to download (use '*' to download all assets other than tarball or zipball)
          fileName: '*'
          out-file-path: './latest-release'
          # Github token to access private repos
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - if: hashFiles('latest-release/*') != hashFiles('electron/dist/*')
        name: Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          name: ${{ steps.now-name.outputs.content }}
          tag_name: ${{ steps.now-tag.outputs.content }}
          body: ${{ join(github.event.commits.*.message, steps.newline.outputs.content) }}
          files: "electron/dist/kernel.asar"
